language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: bash build.sh
deploy:
  provider: pypi
  user: dodilon
  on:
    branch: master
    tags: true
    repo: DenisTheDilon/simple-gomatic
  password:
    secure: iGYAnHBMHWB/2ijrNbaR5/d8obr4BiZJVSpHYz9AbQVAez2/6acXM1g2Ak4s/N0Fh49LCXMIUx5XYDqwcRWAeSkQ2MikxqbVRKAByTsIt0zXJQJrCFA2FhtkhBb5P0o+IpsTx9eNqr7nIyUpOXU7oWrbUl1zxOR7m0/kfnxirPY=
